Fix for issue #3
sindresorhus/p-tap pull request #4
Opened 2017-12-30 12:21 UTC by VamshiKrishnaAlladi

`pTap` and `pTap.catch` methods do not ignore errors thrown in tap callbacks anymore.

2017-12-30 12:35 UTC, sindresorhus commented
You need to update the docs too :)

2017-12-30 12:36 UTC, VamshiKrishnaAlladi commented
Doing it right away.

2017-12-30 12:58 UTC, VamshiKrishnaAlladi commented
Done. 👍

2018-01-05 05:37 UTC, VamshiKrishnaAlladi commented
Hi @sindresorhus, Hope you had a good new year bash.

I've updated the docs with the changes. Are those changes ok? Do I have to change anything there?

Don't get me wrong. I am just excited about my first OSS contribution. 😁 🤞

2018-02-04 04:35 UTC, VamshiKrishnaAlladi commented
Hey @sindresorhus, it's been almost a month now. Can you merge this PR, please? Do I need to change anything here?

2018-03-09 08:10 UTC, VamshiKrishnaAlladi commented
Hey @sindresorhus, any updates on this?

2018-03-09 08:25 UTC, SamVerschueren requested changes

2018-03-09 08:25 UTC, SamVerschueren commented on readme.md
> +Any return value is ignored.
I believe this would be better.

> Any return value is ignored. Exceptions throw in `input` are relayed back to the original promise chain.

2018-03-09 08:50 UTC, VamshiKrishnaAlladi commented on readme.md
> +Any return value is ignored.
Done 👍

2018-03-09 09:12 UTC, VamshiKrishnaAlladi commented
Done 👍 Fixed the XO lint error also. Travis builds pass now.

2018-03-09 10:09 UTC, SamVerschueren approved these changes
LGTM

2018-06-06 07:21 UTC, 5c077yP commented
could we merge this ?

2018-06-09 09:45 UTC, merged